# Generated by Django 6.0.6 on 2026-06-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='custom_alias',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
