# Generated by Django 6.0.6 on 2026-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shortenedurl_custom_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
